config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  get 'static_pages/payment'
  
  resources :charges
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end 

  def create
    # Aount in cents
    @amount = 300
    Stripe.api_key = "sk_live_RO6YQnVh9pfjkyyF9xxGhJNa"
    customer = Stripe::Customer.create(
        :email => 'legraphiste@gmail.com',
        :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
        :customer => customer.id,
        :amount => @amount,
        :description => 'Rails stripe customer',
        :currency => 'chf'
    )

    rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to charge_path
  
 end   
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def payment
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <b>$3.00</b>!!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
    <article>
        <label class="amount">
            <span>Amount : $3.00</span>
        </label>
    </article>

    <script src="https://checkout.stripe.com/checkout.js"
            class="stripe-button"
          
            data-name="MyShop"
            data-key="pk_live_h3IAnPyNABlfgHaXEvitSFQF"
            data-description="A month's subscription"
            data-amount="300">
      
    </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title><%= yield(:title) %> | Stripe Test App</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<h1>Sample Payment App</h1>
<p>This page will allow to test stripe payment.</p>

app/views/static_pages/payment.html.erb
<% provide(:title, "Payment") %>
<h1>Make a payment</h1>

<p>This page allows you to make a payment</p>